name: Main
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Render Video
        uses: andrewmarklloyd/math-visual-proofs-action@main
        env:
          CLOUDMQTT_MATH_PROOFS_AGENT_USER: ${{ secrets.CLOUDMQTT_MATH_PROOFS_AGENT_USER }}
          CLOUDMQTT_MATH_PROOFS_AGENT_PASSWORD: ${{ secrets.CLOUDMQTT_MATH_PROOFS_AGENT_PASSWORD }}
          CLOUDMQTT_URL: ${{ secrets.CLOUDMQTT_URL }}
        with:
          fileName: MovingAround.py
          className: MovingAround
          repoURL: https://github.com/andrewmarklloyd/math-vis-proofs-test.git
